#!/usr/bin/env bash

#This script assumes your flake is in ~/.dotfiles and that your flake's nixosConfigurations is named the same as your $hostname
cd ~/.dotfiles || { echo "Failed to change directory"; exit 1; }

build_output=$(nix flake lock --update-input nixpkgs && nix build --dry-run .#nixosConfigurations.$HOSTNAME.config.system.build.toplevel 2>&1)

# Extract information about fetched paths
fetched_info=$(echo "$build_output" | awk '/will be fetched/ {flag=1; next} flag && /^[[:space:]]*\/nix\/store/ {print}')

# Count the number of fetched paths
total_updates=$(echo "$fetched_info" | grep -E '^[[:space:]]+/nix/store/' | wc -l)

# Extract the sizes of fetched paths
fetched_size=$(echo "$build_output" | grep -oP '\(\K[^)]+(?=\))' | tr '\n' ' ')

# Output the result in the desired format
echo "{ \"text\":\"$total_updates\", \"tooltip\":\"$fetched_size\" }"
